.TH allcm 1 "11/94" "teTeX" "teTeX"
.SH NAME
allcm \- force the most important Computer\-Modern\-fonts to be calculated
.SH SYNOPSIS
.B allcm
.SH DESCRIPTION
.I allcm
forces a large number of Computer Modern Fonts to be calculated as pixel files.
This is done through running
.IR dvips (1)
over a certain test\-file. Therefore, the fonts are created in the resolution
needed by dvips.

.I allec
does not recalculate existing fonts (as long as the Metafont mode does not change).

.SH "SEE ALSO"
allec(1),
allneeded(1),
fontimport(1),
fontexport(1).

.SH AUTHOR
Thomas Esser (te@dbs.uni\-hannover.de)
