________________________
THE EU ENCODING(S) v0.1e

Warning: don't install this package with Latin Modern fonts prior to
version 1.106, which was released in Feb 2008.

This package is the first release of the first step towards offering a
LaTeX font encoding based on unicode. XeTeX is the only engine currently
utilising it to the best of my knowledge. No macro support is offered (the
encoding is just a placeholder for now) but an EU1 Latin Modern encoding is
offered in order to access the OpenType versions of those fonts.

N.B. This will only work when xdvipdfmx is used as the output driver for
XeTeX; xdv2pdf (Mac OS X only) does not support OpenType fonts that aren't
installed in the system itself. As of XeTeX v0.997, xdv2pdf is no longer
the default driver in Mac OS X.

Usually you'll just want to use fontspec:
\documentclass{article}
\usepackage{fontspec}
\begin{document}
...
\end{document}

Example of use without fontspec:
\documentclass{article}
\usepackage[EU1]{fontenc}
\usepackage{lmodern}
\begin{document}
...
\end{document}

See the accompanying file <test-eu1lm.ltx> for a complete example.

____________
INSTALLATION

CTAN contains the necessary files to install for this package:
  - eu1enc.def
  - lm/eu1lm*.fd (* is a wild card: six files in all)
These should be placed in $TEXMF/tex/xelatex/euenc .

To generate these files from the euenc.dtx file, first run `latex eu1enc.ins`.
This will extract the eu1enc.def file and a slew of shell scripts that
create the lm/eu1lm*.fd files. These .fd files are generated by executing
`sh convert-lmfd.sh`.

______________
Will Robertson
2007-2008
