/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sil_scripts_teckit_TecKitJni */

#ifndef _Included_org_sil_scripts_teckit_TecKitJni
#define _Included_org_sil_scripts_teckit_TecKitJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sil_scripts_teckit_TecKitJni
 * Method:    createConverter
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_org_sil_scripts_teckit_TecKitJni_createConverter
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_sil_scripts_teckit_TecKitJni
 * Method:    convert
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_sil_scripts_teckit_TecKitJni_convert
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_sil_scripts_teckit_TecKitJni
 * Method:    flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sil_scripts_teckit_TecKitJni_flush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_sil_scripts_teckit_TecKitJni
 * Method:    destroyConverter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sil_scripts_teckit_TecKitJni_destroyConverter
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
